### ISSUE TITLE
Provide a DC class for getting text metrics only

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#12486]
*Issue migrated from trac ticket # 12486*

**component:** GUI-all | **priority:** low | **keywords:** MemoryDC text-extent simple

#### 2010-09-18 13:30:44: elvisjohndowson (Elvis John Dowson) created the issue

___
Hi,
      I have a problem with wxWidgets/WxPython-2.8.81 and 2.8.11.0, when using it with the GNU Radio library, where calls to memory device contexts to get the text extents fail, like this:

$ python scopesink_gl.py

input rate 1000000.0  v_scale None  t_scale 3e-05
Traceback (most recent call last):
 File "/Users/elvis/Tool/gnuradio-next/gr-wxgui/src/python/plotter/plotter_base.py", line 187, in _on_paint
   for fcn in self._draw_fcns: fcn[1]()
 File "/Users/elvis/Tool/gnuradio-next/gr-wxgui/src/python/plotter/plotter_base.py", line 59, in draw
   self._draw()
 File "/Users/elvis/Tool/gnuradio-next/gr-wxgui/src/python/plotter/grid_plotter_base.py", line 204, in _draw_grid
   for tick in self._get_ticks(self.x_min, self.x_max, self.x_step, self.x_scalar)]
 File "/Users/elvis/Tool/gnuradio-next/gr-wxgui/src/python/plotter/grid_plotter_base.py", line 302, in _get_tick_label
   return gltext.Text(tick_str, font_size=TICK_TEXT_FONT_SIZE)
 File "/Users/elvis/Tool/gnuradio-next/gr-wxgui/src/python/plotter/gltext.py", line 340, in __init__
   self._initText()
 File "/Users/elvis/Tool/gnuradio-next/gr-wxgui/src/python/plotter/gltext.py", line 376, in _initText
   self._centered)
 File "/Users/elvis/Tool/gnuradio-next/gr-wxgui/src/python/plotter/gltext.py", line 73, in __init__
   self.createTexture()
 File "/Users/elvis/Tool/gnuradio-next/gr-wxgui/src/python/plotter/gltext.py", line 160, in createTexture
   ow, oh = dc.GetMultiLineTextExtent(self._text)[:2]
 File "//usr/local/lib/wxPython-unicode-2.8.11.0/lib/python2.6/site-packages/wx-2.8-mac-unicode/wx/_gdi.py", line 3774, in GetMultiLineTextExtent
   return _gdi_.DC_GetMultiLineTextExtent(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Ok()" failed at /BUILD/wxPython-src-2.8.11.0/src/common/dcgraph.cpp(880) in DoGetTextExtent(): wxGCDC(cg)::DoGetTextExtent - invalid DC
Terminated

In the file gr-wxgui/src/python/plotter/gltext.py, line number 160, the call to GetMultiLineTextExtent fails.

ow, oh = dc.GetMultiLineTextExtent(self._text)[:2]

I tried using 

ow, oh = dc.GetTextExtent(self._text)[:2]

as suggested by the report here: http://trac.flipturn.org/ticket/620

but that also failed.

Since I was eager to see if gnuradio and wxPython-2.8, manually compiled to run natively using carbon framework (to avoid getting into the OpenGL API context call changes in wxPython-2.9), I simply over-rode the variables :

       ow = 10
       oh = 10

to just test to see if OpenGL was working, and sure enough, it works, as seen in the attached file.

Is there a recommended solution or workaround to the fix for the dc.GetTextExtent issue?

best regards,

Elvis Dowson

**Comment by vadz** [comment]
I'm returning to the idea of providing `wxInfoDC` as currently we can't deprecate `wxClientDC` even though it doesn't work for drawing any longer because it can also be used for just getting the information about the DC (see 2a368fec9f (Document that using wxClientDC for drawing is not portable, 2020-06-27)).

So it would be nice to provide `wxInfoDC` and replace the "legitimate" uses of `wxClientDC` with it and then deprecate this class (and also `wxWindowDC` and `wxScreenDC`).

Comments or help welcome!

**Comment by vadz** [comment]
Done in 3d776fdad44b5e14a65991c35e5893a705e188df, see #24715.
