### ISSUE TITLE
wxWidget 3.1.7: hangs in assertion dialog

### ISSUE THREAD

**Issue by PMaff** [wxWidgets/wxWidgets#22596]
**To Reproduce**
See
https://github.com/wxWidgets/wxWidgets/issues/22550

**Platform and version information**
 - wxWidgets version 3.1.7
 -Ubuntu 22.04 'jammy'
Linux machinename 5.15.0-37-generic ...

See more information here:
https://github.com/wxWidgets/wxWidgets/issues/22550

and
https://github.com/wxWidgets/wxWidgets/issues/22550#issuecomment-1159487579

**Comment by PMaff** [comment]
> The originally reported problem is fixed now (thanks Paul) and I've also added the missing bitmaps, but if you have any information into why the asserts resulted in the application hanging, please open a new issue for this because this is still definitely not expected. TIA!

@vadz : I tried the new version wxWidget 3.2.0.0 from the current trunk and there the webview example works.

So if it is still urgent to find the hanging assertion dialog I would need your help:
which version of wxWidget 3.1.7 shall I check out to try this?
I guess the first breakpoint would be in `bool WebApp::OnInit()` ?

**Comment by oneeyeman1** [comment]
Hi,
If you can try and go back to the previous version, build and run the webview sample, make it hang, attach gdb/lldb to the process and get a backtrace it would be great.

**Comment by vadz** [comment]
You should be able to reproduce the original problem simply by reverting the commit with the fix, i.e. `git revert -n 33c2de748a15e93d563e06e43aef368d5c04c634` (`-n` avoids committing the revert, once you will have finished testing you can do `git revert --abort` to undo the change).

As for debugging, I'd start by putting a breakpoint on `wxDefaultAssertHandler` and check if it's triggered again after hitting it the first time. If it is, please use `bt` gdb command (BTW, I think it might be better to do it from gdb rather than another GUI application, but maybe using ddd would work too) to see how does this happen.

TIA!

**Comment by PMaff** [comment]
Was a bit busy but here we go: 
I had the previous 3.1.7 still in my virtual machine so I was able to reproduce the error without reverting.
See also attached screenfilm, where you can see the problem after the final window pops up and still
an assertion dialog comes afterwards:

https://user-images.githubusercontent.com/93879362/178040705-d6dba603-2514-421b-a068-6bb689777d01.mp4


Single stepping through the assert dialogs with ddd [...]:
```
[...]
Thread 1 "webview" hit Breakpoint 1, 0x0000555555aca5c0 in wxDefaultAssertHandler(wxString const&, int, wxString const&, wxString const&, wxString const&) ()
(gdb) step
Single stepping until exit from function _ZL22wxDefaultAssertHandlerRK8wxStringiS1_S1_S1_,
which has no line number information.
__GI___libc_free (mem=0x0) at ./malloc/malloc.c:3352
(gdb) step
3356	in ./malloc/malloc.c
(gdb) step
0x0000555555aca617 in wxDefaultAssertHandler(wxString const&, int, wxString const&, wxString const&, wxString const&) ()
(gdb) step
Single stepping until exit from function _ZL22wxDefaultAssertHandlerRK8wxStringiS1_S1_S1_,
which has no line number information.
../src/gtk/bitmap.cpp(970): assert ""IsOk()"" failed in GetWidth(): invalid bitmap

^C
Thread 1 "webview" received signal SIGINT, Interrupt.
0x00007ffff219e168 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff219e168 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff219ff3b in g_main_context_check () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff21f463d in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff219f293 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff3dbcba7 in gtk_dialog_run () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00005555558ebc6a in wxGUIAppTraits::ShowAssertDialog(wxString const&) ()
#6  0x0000555555aca1c7 in ShowAssertDialog(wxString const&, int, wxString const&, wxString const&, wxString const&, wxAppTraits*) ()
#7  0x0000555555aca4a9 in wxAppConsoleBase::OnAssertFailure(wchar_t const*, int, wchar_t const*, wchar_t const*, wchar_t const*) ()
#8  0x00005555558cc9e4 in wxApp::OnAssertFailure(wchar_t const*, int, wchar_t const*, wchar_t const*, wchar_t const*) ()
#9  0x0000555555aca683 in wxDefaultAssertHandler(wxString const&, int, wxString const&, wxString const&, wxString const&) ()
#10 0x0000555555ac8a1f in wxOnAssert(char const*, int, char const*, char const*, wchar_t const*) ()
#11 0x00005555558cdbd3 in wxBitmap::GetWidth() const ()
#12 0x000055555592a793 in wxBitmapBase::GetLogicalWidth() const ()
#13 0x0000555555a2a94b in wxGtkImageDraw ()
#14 0x00007ffff3fa7b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff3d88825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff3d8892d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff3d2a571 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff3d802e1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff3d94852 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff3d2ae15 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff3fa7b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff3d88825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff3d8892d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff3d44391 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007ffff3d802e1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007ffff3d94852 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff3d41705 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff3fa7b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff3d88825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff3d8892d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007ffff3fa7b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007ffff3d88825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007ffff3f53b9d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#34 0x00007ffff3d802e1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#35 0x00007ffff3d94852 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#36 0x00007ffff3f4f9e5 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007ffff3fa7b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007ffff3d88825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007ffff3d8892d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007ffff3ddb1c0 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00007ffff3fa7b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#42 0x00007ffff3d88825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#43 0x00007ffff3d8892d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#44 0x00007ffff3d2a571 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#45 0x00007ffff3d802e1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#46 0x00007ffff3d94852 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#47 0x00007ffff3d2ae15 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#48 0x00007ffff3fa7b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#49 0x00007ffff3d88825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#50 0x00007ffff3d8892d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#51 0x00007ffff3fc860e in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#52 0x00007ffff3fa7b64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#53 0x00007ffff3fb3db1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#54 0x00007ffff3e5a54b in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#55 0x00007ffff207c743 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#56 0x00007ffff208f151 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#57 0x00007ffff2094221 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#58 0x00007ffff2094418 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#59 0x00007ffff22b8640 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#60 0x00007ffff22b87a3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#61 0x00007ffff2089c6f in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#62 0x00007ffff20762ad in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#63 0x00007ffff21a02a8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#64 0x00007ffff219fc24 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#65 0x00007ffff21f46f8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#66 0x00007ffff219f293 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#67 0x00007ffff3e50cfd in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#68 0x0000555555a28c85 in wxGUIEventLoop::DoRun() ()
#69 0x0000555555af9511 in wxEventLoopBase::Run() ()
#70 0x0000555555ac8c99 in wxAppConsoleBase::MainLoop() ()
#71 0x0000555555b46217 in wxEntry(int&, wchar_t**) ()
#72 0x000055555585afa6 in main ()
(gdb)
```

**Comment by vadz** [comment]
Thanks for debugging it, but I think it's just due to showing an assert every time the toolbar is repainted in 3.1.7. I.e. it's not something fundamentally wrong, but just due to a wrong assert, which was already removed and so there doesn't seem to be anything else to be done here.

Thanks again for your help!
