### ISSUE TITLE
wxGTK can crash when starting a drag while the drag icon is animating (3.3)

### ISSUE THREAD

**Issue by pieter3d** [wxWidgets/wxWidgets#24677]
Seen at top-of-tree as of today, ubuntu 22.04 LTS.

When starting a drag from (in my experiment) a wxListBox, a little document icon appears by the mouse to indicate something is being dragged. When the drag is released within the same originating wxWindow (the list in my case), the document icon fades out to indicate end-of-drag. If however a new drag is started while that animation is going on, the application crashes. The crash originates from `src/gtk/bitmap.cpp` line 1403:
```c++
void wxBitmap::Draw(cairo_t* cr, int x, int y, bool useMask, const wxColour* fg, const wxColour* bg) const
{
    wxCHECK_RET(IsOk(), "invalid bitmap");
```

The calling function is in dnd.cpp, the draw call in 

```c++
#ifdef __WXGTK3__
extern "C" {
static gboolean draw_icon(GtkWidget*, cairo_t* cr, wxIcon* icon)
{
    icon->Draw(cr, 0, 0);
    return true;
}
}
#endif
```
Moving up the stack trace is all system GTK lib calls until eventually the wxWidgets event loop.

This doesn't happen if I use the system installed wxWidgets library, but that's version 3.0. I did notice that with 3.0 there are no animating drag/drop document icons

**Comment by paulcor** [comment]
Does this fix it?
```diff
diff --git a/src/gtk/dnd.cpp b/src/gtk/dnd.cpp
index b5b64dd995..a9c9117177 100644
--- a/src/gtk/dnd.cpp
+++ b/src/gtk/dnd.cpp
@@ -928,6 +928,10 @@ wxDragResult wxDropSource::DoDragDrop(int flags)
 
     g_signal_handlers_disconnect_by_func (m_iconWindow,
                                           (gpointer) gtk_dnd_window_configure_callback, this);
+#ifdef __WXGTK3__
+    g_signal_handlers_disconnect_matched(
+        m_iconWindow, G_SIGNAL_MATCH_FUNC, 0, 0, nullptr, (void*)draw_icon, nullptr);
+#endif
     g_object_unref(m_iconWindow);
     m_iconWindow = nullptr;
 
```

**Comment by pieter3d** [comment]
Doesn't look like helps. Same behavior. Stack trace:

```c++
#0  0x00005555561a5a90 in  ()
#1  0x0000555555974a1b in wxBitmap::Draw(_cairo*, int, int, bool, wxColour const*, wxColour const*) const (this=0x7fffffffd058, cr=0x555556446c00, x=0, y=0, useMask=true, fg=0x0, bg=0x0) at external/wxWidgets/src/gtk/bitmap.cpp:1403
#2  0x00005555559823d6 in draw_icon(GtkWidget*, cairo_t*, wxIcon*) (cr=0x555556446c00, icon=0x7fffffffd058) at external/wxWidgets/src/gtk/dnd.cpp:699
#3  0x00007ffff7b55ee8 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff7aff111 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007ffff728d700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff728d863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff7b0edb2 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff78ef835 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff78ef93d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff7b2f63e in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff7b0eb94 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff7b1ade1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff79c157b in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff76a1743 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#15 0x00007ffff76b4151 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#16 0x00007ffff76b9221 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#17 0x00007ffff76b9418 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#18 0x00007ffff728d700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff728d863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff76aec6f in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#21 0x00007ffff769b2ad in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#22 0x00007ffff71772c8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff7176c44 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff71cc2b8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff71762b3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff79b7d2d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x0000555555abb8e1 in wxGUIEventLoop::DoRun() (this=0x5555565dd770) at external/wxWidgets/src/gtk/evtloop.cpp:61
#28 0x0000555555756fec in wxEventLoopBase::Run() (this=0x5555565dd770) at external/wxWidgets/src/common/evtloopcmn.cpp:87
#29 0x00005555557273d0 in wxAppConsoleBase::MainLoop() (this=0x555555fadde0) at external/wxWidgets/src/common/appbase.cpp:362
#30 0x00005555557270eb in wxAppConsoleBase::OnRun() (this=0x555555fadde0) at external/wxWidgets/src/common/appbase.cpp:280
#31 0x000055555585743d in wxAppBase::OnRun() (this=0x555555fadde0) at external/wxWidgets/src/common/appcmn.cpp:349
#32 0x000055555578b79e in wxEntry(int&, wchar_t**) (argc=@0x555555edab40: 1, argv=0x555555f85960) at external/wxWidgets/src/common/init.cpp:585
#33 0x000055555578b896 in wxEntry(int&, char**) (argc=@0x7fffffffddb4: 1, argv=0x555555f2ff40) at external/wxWidgets/src/common/init.cpp:596
#34 0x00005555556c0c4b in main(int, char**) (argc=3, argv=0x7fffffffdf58) at src/main.cc:23

```

**Comment by paulcor** [comment]
How about this?
```diff
diff --git a/src/gtk/dnd.cpp b/src/gtk/dnd.cpp
index b5b64dd995..1380308f57 100644
--- a/src/gtk/dnd.cpp
+++ b/src/gtk/dnd.cpp
@@ -928,6 +928,16 @@ wxDragResult wxDropSource::DoDragDrop(int flags)
 
     g_signal_handlers_disconnect_by_func (m_iconWindow,
                                           (gpointer) gtk_dnd_window_configure_callback, this);
+#ifdef __WXGTK3__
+    GtkWidget* drawWidget = m_iconWindow;
+    if (gtk_check_version(3,20,0) == nullptr)
+        drawWidget = gtk_bin_get_child(GTK_BIN(drawWidget));
+    if (drawWidget)
+    {
+        g_signal_handlers_disconnect_matched(
+            drawWidget, G_SIGNAL_MATCH_FUNC, 0, 0, nullptr, (void*)draw_icon, nullptr);
+    }
+#endif
     g_object_unref(m_iconWindow);
     m_iconWindow = nullptr;
 
```

**Comment by pieter3d** [comment]
That seems to do the trick. Is that a robust solution? What happens for other versions?

**Comment by vadz** [comment]
As the fix has been pushed to master, I'm closing this. I'll also back port it to 3.2.
